version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  setup-workflow:
    when: [ gitlab-flow, << pipeline.git.branch >> ]
    jobs:
      - path-filtering/filter:
          base-revision: remotes/origin/production
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true

  setup-workflow-2:
    when: [ master, << pipeline.git.branch >> ]
    jobs:
      - path-filtering/filter:
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true

  setup-workflow-3:
    when: [ master, << pipeline.git.branch >> ]
    jobs:
      - path-filtering/filter:
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true

