version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  setup-workflow:
    when: [ gitlab-flow, << pipeline.git.branch >> ]
    jobs:
      - path-filtering/filter:
          base-revision: remotes/origin/production
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true
#           filters:
#             branches:
#               only: gitlab-flow

  setup-workflow-2:
    when: [ master, << pipeline.git.branch >> ]
    jobs:
      - path-filtering/filter:
          name: test
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true
#           filters:
#             branches:
#               only: master

  setup-workflow-3:
    jobs:
      - path-filtering/filter:
          name: test2
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true
          filters:
            branches:
              only: master-2
