version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@dev:alpha

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: << pipeline.git.branch >>
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true
