version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  setup-workflow:
    jobs:
      - path-filtering/filter:
          base-revision: remotes/origin/production
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true
      - path-filtering/filter:
          name: test
          mapping: |
            src/server/.* build-server true
            src/client/.* build-client true
